### ISSUE TITLE
issues when needing to run as root

### ISSUE THREAD

**Issue by seertenedos** [sabrsorensen/alpine-cloudplow#2]
I am not sure if i am the only one but i get a lot of files from different sources in my upload folders so i need to run as root to be able to make sure i can fully access them and delete after upload. to do this i set uid and gid to 0 as per your sample for setting the user. Some of the issues are not exactly related to root but should not be needed with root

The issues
1. The permissions on all files under /config are changed. I find it annoying for the cloudplow config file but for the rclone config and service accounts it means i need to pass them in as read-only mounts and get a heap of errors reported. If i don't pass rclone and service accounts as read only my rclone containers that use the same config file for mounting the drives fail as they loose access to the files. My understanding is this permission setting should not be needed if running as root.
2. To get around the permission issue in 1 above i tried putting rclone config at /rclone_config and service accounts at /service_accounts and updated configs to match. The result was everything started but it never reported finding any jobs or any errors and never did anything. Also tried setting the files to 777 in case it was a permission issue but had no effect. To be clear i changed the rclone config location in the cloudplow config to match.

with the read only mount hack above for rclone config and service accounts everything is running great now but it just feels a bit clunky.

**Comment by sabrsorensen** [comment]
I've seen it generally considered a best practice not to run services/containers as root if at all possible, and I've tried designing this container around that practice. 

That being said, since cloudplow supports running as root and you need to run as root, then this container should support running as root without any clunkiness, but in the meantime while I work on improving the support, you might consider these workarounds:

I also deal with files from multiple sources/user accounts, and I've used a combination of default ACLs and the group sticky bit on my upload directories and assigning all user accounts for the services I run to the same primary "media" group to address some of the file permissions issues you've mentioned:
`# chgrp -R media /upload/directory` to change group ownership of my upload directories to media.
`# chmod g+s -R /upload/directory` to recursively set the sticky bit on the upload directory so that all new files are owned by the media group.
`# setfacl -dm "g:media:rwx" -R /upload/directory` to recursively grant the media group with RWX permissions.
`# usermod -a -G media cloudplow` to add cloudplow to the media group.

I use a unique client ID and secret for my Cloudplow rclone config, maintained in a config file used only by Cloudplow, however I can see how being able to share config files between containers would be convenient. I will adjust the init scripts to be less restrictive with permissions and less aggressive with changing ownership, which should address the need to mount configs as read-only.

I'm not sure why changing the config paths to /rclone_config and /service_accounts wouldn't work. If you're still able to reproduce this configuration, could you try setting the environment variable `CLOUDPLOW_LOGLEVEL` to `DEBUG` in your container and sharing the logs? Cloudplow should provide more detail when trying to run with the modified config locations and we might be able to track that issue down.

**Comment by seertenedos** [comment]
I will give the debug a go tonight.  With the settings on the upload directory i can try them but i am not sure if it will work as the directory is under mergerfs running in a docker passed though as a mount that also runs over 6 rclone mounts. If i get a change i will try to test it tonight with trying to get the same group and maybe user everywhere. 

As to the config files what is you used the uid and gid provided for setting the owner and group for the files and only changed the owner permissions to the files if needed and left the other permissions as it. Actually you would only need to change the owner right?

I agree it is great to not run as root it is just i always seem to end up in access/permission hell especially when docker created the directories it mounts into the images or different containers having different groups and group numbers.

**Comment by sabrsorensen** [comment]
I believe applying the upload directory settings through a mergerfs mount to the underlying filesystems is possible, and mergerfs will still respect the settings if applied directly to some but not all of the underlying filesystems.

I'm using the s6-overlay init and process management system in the container, which is also handling the permissions/ownership changes. I can relax the permissions on /config pretty easily so editing config.json won't require root. 

At this point, I don't see a way via s6-overlay to exclude the rclone config and service account files from the cloudplow config ownership changes if they're all stored under /config, so I think emulating your separated /rclone_config and /service_accounts mounts for storing these rclone config files may be the best way to preserve the ownership/permissions of these files. s6-overlay also seems to require setting both the group and owner, so it wouldn't be possible to change just the owner using the s6-overlay fix-attrs.d system. I'll update the documentation and modify the image with these changes.

Permission hell is a huge pain, I just redid my server a month or so ago and I'm still sorting out the correct default permissions on some things :-/

**Comment by sabrsorensen** [comment]
@seertenedos I've triggered a new build of sabrsorensen/alpine-cloudplow:develop which should have better support for running as root without clobbering the permissions/ownership of the rclone/service account files, mounted under /rclone_config and /service_accounts as mentioned above. Please try it out and let me know if it resolves your issues, in my testing /config was owned by root:root however config.json had 666 permissions so it was world-writable.

**Comment by seertenedos** [comment]
That sounds perfect. i will test it tonight

**Comment by seertenedos** [comment]
very nice! but i seem to get an upload issue once the upload triggers. Not sure if it was because i had no files to upload. It seems if finds the service accounts in /service_accounts but when it adds the service account to the move command it puts a /config in front of it so it can't find the service account

```
- Using service account: '/config/service_accounts/1.json'
cloudplow           | 2019-12-03 17:40:47,206 - INFO       - uploader             - upload                         - Uploading '/data/vid_4k' to remote: vid4k
cloudplow           | 2019-12-03 17:40:47,206 - DEBUG      - rclone               - upload                         - Uploading '/data/vid_4k' to 'vid4k_crypt:'
cloudplow           | 2019-12-03 17:40:47,206 - DEBUG      - rclone               - upload                         - Rclone command set to 'move'
cloudplow           | 2019-12-03 17:40:47,206 - DEBUG      - rclone               - upload                         - Using: /usr/bin/rclone move /data/vid_4k vid4k_crypt: --config=/rclone_config/rclone.conf --drive-service-account-file /config/service_accounts/1.json --checkers=16 --drive-chunk-size=64M --skip-links --stats=60s --transfers=8 --user-agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36' --verbose=1 --exclude='**partial~' --exclude='**_HIDDEN~' --exclude='.unionfs/**' --exclude='.unionfs-fuse/**'
cloudplow           | 2019-12-03 17:40:47,259 - INFO       - process              - execute                        - 2019/12/03 17:40:47 Failed to create file system for "vid4k_crypt:": failed to make remote vid4k:"" to wrap: drive: failed when making oauth client: error opening service account credentials file: open /config/service_accounts/1.json: no such file or directory

```

**Comment by sabrsorensen** [comment]
I haven't used service accounts before, I'll give it a try with my instance and see if I can reproduce it on my end. Using no service accounts and my cloudplow UID and media GID as opposed to root, this :develop image is able to successfully upload on my machine. I'll try running as root as well, that may be a factor.

In the meantime, would you mind sharing your cloudplow config.json, or at least snippets of one of the remotes and the corresponding uploader section?

**Comment by sabrsorensen** [comment]
I had to add the `--drive-impersonate user@domain.com` argument to my rclone arguments to get the service accounts to work when I had them added under /config/service_accounts/.

Mounting the service account files under /service_accounts/ reproduces the same failure you're seeing, /config is being prefixed to the service accounts path. I'll look into how cloudplow reads this config setting and see if the issue lies there.

**Comment by seertenedos** [comment]
slightly modified config. just removed a few of the uploads and and changed some names
[config](https://gist.github.com/seertenedos/5c3507cc23cc915b22c96d734b8318bb)

**Comment by sabrsorensen** [comment]
@seertenedos try stopping your buttplow container, deleting cache.db from your config directory, and restarting buttplow to clear out any memory of your service account files previously being located under /config/service_accounts. I suspect that buttplow may not invalidate its list of service accounts if the files are no longer at the expected location, in turn passing the original/stale service account file to rclone.

Edit: Thanks for posting your config! We have similar setups, so I'm pretty confident this is an issue with a stale caching of the service account files.

**Comment by sabrsorensen** [comment]
@seertenedos I've generated another :develop image with my fixes to cloudplow's service account caching, please give it a try with CLOUDPLOW_LOGLEVEL set to DEBUG and verify that you see log entries for removing any stale service accounts.

**Comment by seertenedos** [comment]
@sabrsorensen  It logs that the old ones could not be found and removes them from the cache.  thanks for fixing it! Sorry for the delay in testing i broke my server yesterday so lost a day fixing it

**Comment by sabrsorensen** [comment]
@seertenedos glad to hear your service accounts are working again, bummer about your server though. Are there any other issues you've encountered while running this container as root? If you feel they have all been addressed, would you mind closing out this issue?

**Comment by seertenedos** [comment]
That is it at the moment thanks for fixing them
