### ISSUE TITLE
Relaunch CI to add new module

### ISSUE THREAD

**Issue by LacazeThomas** [sabrsorensen/alpine-cloudplow#26]
Hi ! 

First thanks you for this amazing docker container. 

But in the latest update cloudplow added a new module (See screenshot). 
So it's possible to add it into the docker container ? Thanks !

![image](https://user-images.githubusercontent.com/19855907/184028054-96343d18-8b64-4fca-9617-308059c2cf29.png)

**Comment by alias86** [comment]
Same plz fix <3

**Comment by LacazeThomas** [comment]
You can use my fork [here](https://hub.docker.com/repository/docker/thomaslacaze/alpine-cloudplow)

https://github.com/LacazeThomas/alpine-cloudplow

**Comment by alias86** [comment]
hehe, I tested an hour ago
Erm, it does run but fails on my remote config

cloudplow       | 2022-09-04 13:43:38,894 - ERROR      - rclone               - upload                         - crypt_tv1 is an invalid remote.

I'm only a noob; otherwise, I wouldn't have deleted the working docker image :)

I map the same rclone config for my mounted rclone volumes ( that works )
thanks for the ping all the same

EDIT 1
And it can read the file at least, so that's working.
I've not edited the rclone config file for some time & is running the latest docker image

EDIT 2
**Ok, it does work; I've just copied my rclone conf file to my cloudplow folder and that works thanks for your time and efforts**

**Comment by sabrsorensen** [comment]
I've re-enabled the scheduled workflows and verified the container runs on my machine. Please open another issue if you run into anything else.
